# Testing trained RL agents

In [1]:
import tensorflow as tf
import configparser
import numpy as np

# Load the RL model from the directory
model_directory = "drl_results/n16_fr_oapsn16_off_size120/model"

checkpoint_prefix = model_directory + "/model.ckpt"

# Load the model from the checkpoint
with tf.compat.v1.Session() as sess:
    # Restore the graph structure from the .meta file
    saver = tf.compat.v1.train.import_meta_graph(checkpoint_prefix + ".meta")
    
    # Restore the weights from the checkpoint
    saver.restore(sess, checkpoint_prefix)
    
    # The model is now loaded into the session
    print("Model restored successfully!")

OMP: Info #155: KMP_AFFINITY: Initial OS proc set respected: 0-15
OMP: Info #216: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #157: KMP_AFFINITY: 16 available OS procs
OMP: Info #158: KMP_AFFINITY: Uniform topology
OMP: Info #287: KMP_AFFINITY: topology layer "LL cache" is equivalent to "socket".
OMP: Info #192: KMP_AFFINITY: 1 socket x 8 cores/socket x 2 threads/core (8 total cores)
OMP: Info #218: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #172: KMP_AFFINITY: OS proc 0 maps to socket 0 core 0 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 1 maps to socket 0 core 0 thread 1 
OMP: Info #172: KMP_AFFINITY: OS proc 2 maps to socket 0 core 1 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 3 maps to socket 0 core 1 thread 1 
OMP: Info #172: KMP_AFFINITY: OS proc 4 maps to socket 0 core 2 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 5 maps to socket 0 core 2 thread 1 
OMP: Info #172: KMP_AFFINITY: OS proc 6 maps to socket 0 core 3 thread 0 
OMP: Info #172: KMP_AFFINITY: OS

INFO:tensorflow:Restoring parameters from drl_results/n16_fr_oapsn16_off_size120/model/model.ckpt
Model restored successfully!


2025-05-12 11:08:55.522963: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2025-05-12 11:08:55.526017: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3193980000 Hz
2025-05-12 11:08:55.526130: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x58830e7fb310 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2025-05-12 11:08:55.526149: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2025-05-12 11:08:55.526240: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [2]:
from state_env import State  # module with environment and dynamics

from RL_brain_pi_deep import DQNPrioritizedReplay  # sumtree version of DQN

Instructions for updating:
non-resource variables are not supported in the long term
Seed used: 1747058935


/home/sofi/Documents/codigos/dynamic_control_for_QST/state_env.py:150: ComplexWarning: Casting complex values to real discards the imaginary part
  action_hamiltonians[mag.index(actions)] = ham


In [3]:
config_file = "config.ini" 
config = configparser.ConfigParser()
config.read(config_file)
env = State()  # environment

[[[  0.   1.   0. ...   0.   0.   0.]
  [  1.   0.   1. ...   0.   0.   0.]
  [  0.   1.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   1.   0.]
  [  0.   0.   0. ...   1.   0.   1.]
  [  0.   0.   0. ...   0.   1.   0.]]

 [[100.   1.   0. ...   0.   0.   0.]
  [  1.   0.   1. ...   0.   0.   0.]
  [  0.   1.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   1.   0.]
  [  0.   0.   0. ...   1.   0.   1.]
  [  0.   0.   0. ...   0.   1.   0.]]

 [[  0.   1.   0. ...   0.   0.   0.]
  [  1. 100.   1. ...   0.   0.   0.]
  [  0.   1.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   1.   0.]
  [  0.   0.   0. ...   1.   0.   1.]
  [  0.   0.   0. ...   0.   1.   0.]]

 ...

 [[  0.   1.   0. ...   0.   0.   0.]
  [  1.   0.   1. ...   0.   0.   0.]
  [  0.   1.   0. ...   0.   0.   0.]
  ...
  [  0.   0.   0. ...   0.   1.   0.]
  [  0.   0.   0. ...   1. 100.   1.]
  [  0.   0.   0. ...   0.   1. 100.]]

 [[  0.   1.   0. ...   0.   0.   0.]
  [  1.   0.

In [4]:

# Inspect the graph to find input and output tensor names
for op in tf.compat.v1.get_default_graph().get_operations():
    print(op.name)

s
Q_target
eval_net/l1/w1/Initializer/random_normal/shape
eval_net/l1/w1/Initializer/random_normal/mean
eval_net/l1/w1/Initializer/random_normal/stddev
eval_net/l1/w1/Initializer/random_normal/RandomStandardNormal
eval_net/l1/w1/Initializer/random_normal/mul
eval_net/l1/w1/Initializer/random_normal
eval_net/l1/w1
eval_net/l1/w1/Assign
eval_net/l1/w1/read
eval_net/l1/b1/Initializer/Const
eval_net/l1/b1
eval_net/l1/b1/Assign
eval_net/l1/b1/read
eval_net/l1/MatMul
eval_net/l1/add
eval_net/l1/Relu
eval_net/l15/w15/Initializer/random_normal/shape
eval_net/l15/w15/Initializer/random_normal/mean
eval_net/l15/w15/Initializer/random_normal/stddev
eval_net/l15/w15/Initializer/random_normal/RandomStandardNormal
eval_net/l15/w15/Initializer/random_normal/mul
eval_net/l15/w15/Initializer/random_normal
eval_net/l15/w15
eval_net/l15/w15/Assign
eval_net/l15/w15/read
eval_net/l15/b15/Initializer/Const
eval_net/l15/b15
eval_net/l15/b15/Assign
eval_net/l15/b15/read
eval_net/l15/MatMul
eval_net/l15/add
ev

In [5]:
input_tensor = tf.compat.v1.get_default_graph().get_tensor_by_name("s:0")
output_tensor = tf.compat.v1.get_default_graph().get_tensor_by_name("eval_net/l2/add:0")

In [6]:
with tf.compat.v1.Session() as sess:
    # Restore the graph structure and weights again
    saver.restore(sess, checkpoint_prefix)

    number_of_episodes = 50
    lth = 80

    best_action_sequences = [[] for i in range(0, 10)]
    best_fidelities = np.zeros(10)

    actionspace = []  # store successful actions
    Qvalue = []  # total reward
    fid_max_vector = []  # max. fidelity in each episode
    t_fid_max_vector = []  # time of max. fidelity
    fid_end_vector = []  # final fidelity
    t_end_vector = []  # time of final fidelity
    success_action_sequences = []  # store successful success_action_seq

    for episode in range(number_of_episodes):
        observation = env.reset()
        newaction = []
        Q = 0
        fid_max = 0
        t_fid_max = 0

        for i in range(lth):  # episode maximum length
            # Use the loaded model to predict the action
            # Correct the shape of the observation before feeding it to the model
            predicted_action = sess.run(output_tensor, feed_dict={input_tensor: np.expand_dims(observation, axis=0)})
            predicted_action = np.argmax(predicted_action)
            newaction.append(predicted_action)

            observation_, reward, done, fidelity = env.step(predicted_action)

            Q += reward  # total reward

            # Save max. fidelity value
            if fidelity > fid_max:
                fid_max = fidelity
                t_fid_max = i

            if done:  # fidelity(reward) larger than threshold
                newaction += [0 for xx in range(lth - len(newaction))]
                print(str(i + 1) + "  " + str(episode) + "  " + str(fidelity))
                actionspace.append(newaction)
                Qvalue.append(Q)
                fid_max_vector.append(fid_max)
                fid_end_vector.append(fidelity)
                t_fid_max_vector.append(t_fid_max)
                t_end_vector.append(i + 1)

                if fid_max > 0.9:
                    success_action_sequences.append(newaction)

                    break

            observation = observation_  # Update current state

        if i == lth - 1:
            actionspace.append(newaction)
            fid_max_vector.append(fid_max)
            fid_end_vector.append(fidelity)
            t_fid_max_vector.append(t_fid_max)
            t_end_vector.append(i + 1)
            Qvalue.append(Q)

            if fid_max > 0.9:
                success_action_sequences.append(newaction)

        if fid_max > min(best_fidelities):
            idx = np.argmin(best_fidelities)
            best_fidelities[idx] = fid_max
            best_action_sequences[idx] = newaction

        print(
            "Episode: %d, Step: %d, Max. Fidelity: %.4f"
            % (episode, i, fid_max)
        )
        episodes = np.arange(0, number_of_episodes)


INFO:tensorflow:Restoring parameters from drl_results/n16_fr_oapsn16_off_size120/model/model.ckpt


OMP: Info #254: KMP_AFFINITY: pid 80711 tid 80757 thread 1 bound to OS proc set 2
OMP: Info #254: KMP_AFFINITY: pid 80711 tid 80776 thread 2 bound to OS proc set 4
OMP: Info #254: KMP_AFFINITY: pid 80711 tid 80777 thread 3 bound to OS proc set 6
OMP: Info #254: KMP_AFFINITY: pid 80711 tid 80778 thread 4 bound to OS proc set 8
OMP: Info #254: KMP_AFFINITY: pid 80711 tid 80779 thread 5 bound to OS proc set 10
OMP: Info #254: KMP_AFFINITY: pid 80711 tid 80780 thread 6 bound to OS proc set 12
OMP: Info #254: KMP_AFFINITY: pid 80711 tid 80781 thread 7 bound to OS proc set 14
OMP: Info #254: KMP_AFFINITY: pid 80711 tid 80782 thread 8 bound to OS proc set 1
OMP: Info #254: KMP_AFFINITY: pid 80711 tid 80783 thread 9 bound to OS proc set 3
OMP: Info #254: KMP_AFFINITY: pid 80711 tid 80785 thread 11 bound to OS proc set 7
OMP: Info #254: KMP_AFFINITY: pid 80711 tid 80787 thread 13 bound to OS proc set 11
OMP: Info #254: KMP_AFFINITY: pid 80711 tid 80784 thread 10 bound to OS proc set 5
OMP: Info

Episode: 0, Step: 79, Max. Fidelity: 0.7661
Episode: 1, Step: 79, Max. Fidelity: 0.7661
Episode: 2, Step: 79, Max. Fidelity: 0.7661
Episode: 3, Step: 79, Max. Fidelity: 0.7661
Episode: 4, Step: 79, Max. Fidelity: 0.7661
Episode: 5, Step: 79, Max. Fidelity: 0.7661
Episode: 6, Step: 79, Max. Fidelity: 0.7661
Episode: 7, Step: 79, Max. Fidelity: 0.7661
Episode: 8, Step: 79, Max. Fidelity: 0.7661
Episode: 9, Step: 79, Max. Fidelity: 0.7661
Episode: 10, Step: 79, Max. Fidelity: 0.7661
Episode: 11, Step: 79, Max. Fidelity: 0.7661
Episode: 12, Step: 79, Max. Fidelity: 0.7661
Episode: 13, Step: 79, Max. Fidelity: 0.7661
Episode: 14, Step: 79, Max. Fidelity: 0.7661
Episode: 15, Step: 79, Max. Fidelity: 0.7661
Episode: 16, Step: 79, Max. Fidelity: 0.7661
Episode: 17, Step: 79, Max. Fidelity: 0.7661
Episode: 18, Step: 79, Max. Fidelity: 0.7661
Episode: 19, Step: 79, Max. Fidelity: 0.7661
Episode: 20, Step: 79, Max. Fidelity: 0.7661
Episode: 21, Step: 79, Max. Fidelity: 0.7661
Episode: 22, Step: 7

In [7]:
run_state(config)

NameError: name 'run_state' is not defined