# Testing trained RL agents

In [1]:
import tensorflow as tf
import configparser
import numpy as np
import os

# Load the RL model from the directory
directory = "drl_results/test3"
# Find the config file in the directory

for file in os.listdir(directory):
    if file.endswith(".ini"):
        config_file = file
        break
    
config = configparser.ConfigParser()
# Read the config file
config.read(directory + "/" + config_file)

# Copy the config file to the current directory
current_directory = os.getcwd()
os.system(f"cp {directory}/{config_file} {current_directory}")


checkpoint_prefix = directory+'/best_model/model.ckpt'

# Load the model from the checkpoint
with tf.compat.v1.Session() as sess:
    # Restore the graph structure from the .meta file
    saver = tf.compat.v1.train.import_meta_graph(checkpoint_prefix + ".meta")
    
    # Restore the weights from the checkpoint
    saver.restore(sess, checkpoint_prefix)
    
    
    # The model is now loaded into the session
    print("Model restored successfully!")

OMP: Info #155: KMP_AFFINITY: Initial OS proc set respected: 0-11
OMP: Info #216: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #157: KMP_AFFINITY: 12 available OS procs
OMP: Info #158: KMP_AFFINITY: Uniform topology
OMP: Info #287: KMP_AFFINITY: topology layer "LL cache" is equivalent to "socket".
OMP: Info #192: KMP_AFFINITY: 1 socket x 6 cores/socket x 2 threads/core (6 total cores)
OMP: Info #218: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #172: KMP_AFFINITY: OS proc 0 maps to socket 0 core 0 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 6 maps to socket 0 core 0 thread 1 
OMP: Info #172: KMP_AFFINITY: OS proc 1 maps to socket 0 core 1 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 7 maps to socket 0 core 1 thread 1 
OMP: Info #172: KMP_AFFINITY: OS proc 2 maps to socket 0 core 2 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 8 maps to socket 0 core 2 thread 1 
OMP: Info #172: KMP_AFFINITY: OS proc 3 maps to socket 0 core 4 thread 0 
OMP: Info #172: KMP_AFFINITY: OS

INFO:tensorflow:Restoring parameters from drl_results/test3/best_model/model.ckpt
Model restored successfully!


In [2]:
from state_env import State  # module with environment and dynamics

from RL_brain_pi_deep import DQNPrioritizedReplay  # sumtree version of DQN

Instructions for updating:
non-resource variables are not supported in the long term
Seed used: 1747682843


/home/sofi/Documentos/codigos/dynamic_control_for_QST/state_env.py:167: ComplexWarning: Casting complex values to real discards the imaginary part
  action_hamiltonians[mag.index(actions)] = ham


In [3]:

env = State()  # environment

[[[  0.   1.   0.   0.   0.   0.   0.]
  [  1.   0.   1.   0.   0.   0.   0.]
  [  0.   1.   0.   1.   0.   0.   0.]
  [  0.   0.   1.   0.   1.   0.   0.]
  [  0.   0.   0.   1.   0.   1.   0.]
  [  0.   0.   0.   0.   1.   0.   1.]
  [  0.   0.   0.   0.   0.   1.   0.]]

 [[100.   1.   0.   0.   0.   0.   0.]
  [  1.   0.   1.   0.   0.   0.   0.]
  [  0.   1.   0.   1.   0.   0.   0.]
  [  0.   0.   1.   0.   1.   0.   0.]
  [  0.   0.   0.   1.   0.   1.   0.]
  [  0.   0.   0.   0.   1.   0.   1.]
  [  0.   0.   0.   0.   0.   1.   0.]]

 [[  0.   1.   0.   0.   0.   0.   0.]
  [  1. 100.   1.   0.   0.   0.   0.]
  [  0.   1.   0.   1.   0.   0.   0.]
  [  0.   0.   1.   0.   1.   0.   0.]
  [  0.   0.   0.   1.   0.   1.   0.]
  [  0.   0.   0.   0.   1.   0.   1.]
  [  0.   0.   0.   0.   0.   1.   0.]]

 [[100.   1.   0.   0.   0.   0.   0.]
  [  1. 100.   1.   0.   0.   0.   0.]
  [  0.   1.   0.   1.   0.   0.   0.]
  [  0.   0.   1.   0.   1.   0.   0.]
  [  0.   0.   0.  

In [4]:

# Inspect the graph to find input and output tensor names
for op in tf.compat.v1.get_default_graph().get_operations():
    print(op.name)

s
Q_target
eval_net/l1/w1/Initializer/random_normal/shape
eval_net/l1/w1/Initializer/random_normal/mean
eval_net/l1/w1/Initializer/random_normal/stddev
eval_net/l1/w1/Initializer/random_normal/RandomStandardNormal
eval_net/l1/w1/Initializer/random_normal/mul
eval_net/l1/w1/Initializer/random_normal
eval_net/l1/w1
eval_net/l1/w1/Assign
eval_net/l1/w1/read
eval_net/l1/b1/Initializer/Const
eval_net/l1/b1
eval_net/l1/b1/Assign
eval_net/l1/b1/read
eval_net/l1/MatMul
eval_net/l1/add
eval_net/l1/Relu
eval_net/l15/w15/Initializer/random_normal/shape
eval_net/l15/w15/Initializer/random_normal/mean
eval_net/l15/w15/Initializer/random_normal/stddev
eval_net/l15/w15/Initializer/random_normal/RandomStandardNormal
eval_net/l15/w15/Initializer/random_normal/mul
eval_net/l15/w15/Initializer/random_normal
eval_net/l15/w15
eval_net/l15/w15/Assign
eval_net/l15/w15/read
eval_net/l15/b15/Initializer/Const
eval_net/l15/b15
eval_net/l15/b15/Assign
eval_net/l15/b15/read
eval_net/l15/MatMul
eval_net/l15/add
ev

In [5]:
input_tensor = tf.compat.v1.get_default_graph().get_tensor_by_name("s:0")
output_tensor = tf.compat.v1.get_default_graph().get_tensor_by_name("eval_net/l2/add:0")
n = 7

In [6]:
with tf.compat.v1.Session() as sess:
    # Restore the graph structure and weights again
    saver.restore(sess, checkpoint_prefix)

    number_of_episodes = 500
    lth = config.getint(
            "system_parameters", "max_t_steps"
        )
    
    print("max_t_steps: ", lth)

    best_action_sequences = [[] for i in range(0, 10)]
    best_fidelities = np.zeros(10)

    actionspace = []  # store successful actions
    Qvalue = []  # total reward
    fid_max_vector = []  # max. fidelity in each episode
    t_fid_max_vector = []  # time of max. fidelity
    fid_end_vector = []  # final fidelity
    t_end_vector = []  # time of final fidelity
    success_action_sequences = []  # store successful success_action_seq

    for episode in range(number_of_episodes):
        # Generate a complex normalized vector of 16 components
        observation = env.reset()

        print(observation)

        
        
        newaction = []
        Q = 0
        fid_max = 0
        t_fid_max = 0

        for i in range(lth):  # episode maximum length
            # Use the loaded model to predict the action
            # Correct the shape of the observation before feeding it to the model
            predicted_action = sess.run(output_tensor, feed_dict={input_tensor: np.expand_dims(observation, axis=0)})
            predicted_action = np.argmax(predicted_action)
            newaction.append(predicted_action)

            observation_, reward, done, fidelity = env.noisy_step(predicted_action)
            print("reward: ", reward , " fidelity: ", fidelity)
            Q += reward  # total reward

            # Save max. fidelity value
            if fidelity > fid_max:
                fid_max = fidelity
                t_fid_max = i

            if done:  # fidelity(reward) larger than threshold
                newaction += [0 for xx in range(lth - len(newaction))]
                print(str(i + 1) + "  " + str(episode) + "  " + str(fidelity))
                actionspace.append(newaction)
                Qvalue.append(Q)
                fid_max_vector.append(fid_max)
                fid_end_vector.append(fidelity)
                t_fid_max_vector.append(t_fid_max)
                t_end_vector.append(i + 1)

                if fid_max > 0.9:
                    success_action_sequences.append(newaction)

                    break

            observation = observation_  # Update current state

        if i == lth - 1:
            actionspace.append(newaction)
            fid_max_vector.append(fid_max)
            fid_end_vector.append(fidelity)
            t_fid_max_vector.append(t_fid_max)
            t_end_vector.append(i + 1)
            Qvalue.append(Q)

            if fid_max > 0.9:
                success_action_sequences.append(newaction)

        if fid_max > min(best_fidelities):
            idx = np.argmin(best_fidelities)
            best_fidelities[idx] = fid_max
            best_action_sequences[idx] = newaction

        print(
            "Episode: %d, Step: %d, Max. Fidelity: %.4f"
            % (episode, i, fid_max)
        )
        episodes = np.arange(0, number_of_episodes)

    print("Mean of fid_max_vector:", np.mean(fid_max_vector))

INFO:tensorflow:Restoring parameters from drl_results/test3/best_model/model.ckpt


max_t_steps:  35
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
reward:  0.026587176651923776  fidelity:  2.490783272253362e-16
reward:  0.025827169044117915  fidelity:  4.447478463777072e-14
reward:  0.025450679556975813  fidelity:  1.0128151103982235e-12
reward:  0.0254217345172928  fidelity:  1.2253333229999905e-10
reward:  0.025713691759523188  fidelity:  4.3103397532940605e-10
reward:  0.026307961946716824  fidelity:  1.11560315415453e-09
reward:  0.02719433127476946  fidelity:  7.974101623770077e-08
reward:  0.028384698293470633  fidelity:  2.383365991761813e-06
reward:  0.029958058907735258  fidelity:  1.8648918708526566e-05
reward:  0.03214636887507736  fidelity:  8.681730858990731e-05
reward:  0.035473511323149395  fidelity:  0.0003021859735595314
reward:  0.04094500464380594  fidelity:  0.000867709542511606
reward:  0.050261741066465505  fidelity:  0.002164738155022634
reward:  0.06600049477622913  fidelity:  0.004839116567818772
reward:  0.09167675202243913  fidelity:  0.009888597263768263

OMP: Info #254: KMP_AFFINITY: pid 114258 tid 114289 thread 1 bound to OS proc set 1
OMP: Info #254: KMP_AFFINITY: pid 114258 tid 114319 thread 2 bound to OS proc set 2
OMP: Info #254: KMP_AFFINITY: pid 114258 tid 114320 thread 3 bound to OS proc set 3
OMP: Info #254: KMP_AFFINITY: pid 114258 tid 114321 thread 4 bound to OS proc set 4
OMP: Info #254: KMP_AFFINITY: pid 114258 tid 114322 thread 5 bound to OS proc set 5
OMP: Info #254: KMP_AFFINITY: pid 114258 tid 114325 thread 8 bound to OS proc set 8
OMP: Info #254: KMP_AFFINITY: pid 114258 tid 114324 thread 7 bound to OS proc set 7
OMP: Info #254: KMP_AFFINITY: pid 114258 tid 114323 thread 6 bound to OS proc set 6
OMP: Info #254: KMP_AFFINITY: pid 114258 tid 114326 thread 9 bound to OS proc set 9
OMP: Info #254: KMP_AFFINITY: pid 114258 tid 114327 thread 10 bound to OS proc set 10
OMP: Info #254: KMP_AFFINITY: pid 114258 tid 114328 thread 11 bound to OS proc set 11
OMP: Info #254: KMP_AFFINITY: pid 114258 tid 114329 thread 12 bound to O

reward:  0.0916767520224392  fidelity:  0.009888597263768268
reward:  0.13160012886847897  fidelity:  0.01872768494949317
reward:  0.1904766940451921  fidelity:  0.03319824525371058
reward:  0.27282278850374997  fidelity:  0.05549201908609984
reward:  0.38236701016921937  fidelity:  0.08795777633185468
reward:  0.5215299507914046  fidelity:  0.13278287599123523
reward:  0.6907214042848762  fidelity:  0.19156555791579993
reward:  0.8871388725462096  fidelity:  0.26482636184532043
reward:  1.1034657962197467  fidelity:  0.35153784171252883
reward:  1.3274315143712483  fidelity:  0.44877282331147966
reward:  1.5426978341642446  fidelity:  0.5515748338221287
reward:  1.7307701532835313  fidelity:  0.6531346865813779
reward:  1.8734201887744846  fidelity:  0.745313908645225
reward:  5.07942762945452  fidelity:  0.8194939431481786
reward:  6.897439084406059  fidelity:  0.8676605959697136
reward:  7.297903361868422  fidelity:  0.8835705326311731
reward:  6.059582092727395  fidelity:  0.863805